version: '2'

services:
  products_api:
    image: registry.gitlab.com/taxpayercorner-vs/microservices/productservice:production
    ports:
     - "8015:8015"
    restart: always
    environment:
     - NODE_ENV=production
